update jfrog credentials on change in gradle properties
collaborationFactory/cplace-asc pull request #69
Opened 2022-02-14 12:27 UTC by stefancplace

- update jfrog credentials on change in gradle properties
- read jfrog credentials from gradle.properties
- added unit/integration tests

2022-02-15 05:54 UTC, stefancplace commented
For testing it is useful to clear the npm cache (`npm cache clean --force`), otherwise cplace packages might be taken from the local cache.
We should definitely test on Windows, could you help here @stophi-dev ?

2022-02-15 13:47 UTC, Kaltenbach requested changes
LGTM - Only two minor things. Didn't test this locally...

2022-02-15 13:47 UTC, Kaltenbach commented on src/model/RegistryInitializer.ts
> +            console.error(cred`✗`, 'Userconfig was found in npmrc but but path can not be extracted');
```suggestion
            console.error(cred`✗`, 'Userconfig was found in npmrc but path can not be extracted');
```

2022-02-15 13:47 UTC, Kaltenbach commented on test/RegistryInitializer.test.ts
> +const gradleProperties='org.gradle.java.home=/Users/stefanstadler/.sdkman/candidates/java/11.0.2-open\n' +
maybe without your local setup 😄

2022-02-16 08:09 UTC, Kaltenbach approved these changes
👍

2022-02-16 08:10 UTC, Kaltenbach commented
Just for me to understand: when would the `.npmrc` created? Neither in the old nor the new version it gets created but is expected to exist already, if I'm not mistaken 😄

2022-02-16 08:39 UTC, stefancplace commented
The OS is asked upfront via "npm config ls -l" where .npmrc is stored (in userconfig key/value pair)
In case npm is not installed it should  -> console.error(cred`✗`, 'No user npmrc found');

2022-02-16 08:52 UTC, Kaltenbach commented
Maybe s.th like a `touch ~/.npmrc` would be good enough - if that exists in the file sync lib.

2022-02-16 09:39 UTC, Kaltenbach approved these changes
Looks good. But still it would be nice to have this tested on Windows.

2022-02-16 16:00 UTC, stophi-dev approved these changes
Looks good. It also fixes the problem with older releases before gradle and therfore makes https://github.com/collaborationFactory/cplace-asc/pull/68 obsolete.

2022-02-18 07:43 UTC, merged